#!/bin/bash
set -e

cd "$(dirname "$0")"
PROJECT_ROOT="$(pwd)"

VERUS_VERSION="${VERUS_VERSION:-0.2025.11.15.db81a74}"
RUST_TOOLCHAIN="${RUST_TOOLCHAIN:-1.91.0}"
INSTALL_DIR="verus-toolchain"

OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS-$ARCH" in
  Linux-x86_64)   PLATFORM="x86-linux" ;;
  Darwin-arm64)   PLATFORM="arm64-macos" ;;
  Darwin-x86_64)  PLATFORM="x86-macos" ;;
  *)
    echo "Error: unsupported platform $OS-$ARCH"
    echo "Supported: Linux x86_64, macOS arm64/x86_64"
    exit 1
    ;;
esac

ASSET="verus-${VERUS_VERSION}-${PLATFORM}.zip"
URL="https://github.com/verus-lang/verus/releases/download/release/${VERUS_VERSION}/${ASSET}"
EXTRACTED_DIR="$INSTALL_DIR/verus-${PLATFORM}"

for cmd in curl unzip; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "Error: '$cmd' is required but not installed"; exit 1; }
done

echo "=========================================="
echo "Setting up Rust toolchain (rustup)"
echo "=========================================="

if [ -f "$HOME/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

# rustup (not just cargo) is required below: a distro cargo without rustup
# cannot install the pinned toolchain, so check for rustup explicitly.
if command -v rustup >/dev/null 2>&1; then
  echo "rustup already installed: $(rustup --version 2>/dev/null | head -1)"
else
  echo "Installing rustup (non-interactive, minimal profile) ..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none --profile minimal
  . "$HOME/.cargo/env"
fi

if rustup toolchain list | grep -q "^${RUST_TOOLCHAIN}-"; then
  echo "Rust toolchain ${RUST_TOOLCHAIN} already installed"
else
  echo "Installing Rust toolchain ${RUST_TOOLCHAIN} (required by Verus ${VERUS_VERSION}) ..."
  rustup toolchain install "${RUST_TOOLCHAIN}" --profile minimal
fi
if ! rustup default 2>/dev/null | grep -q .; then
  rustup default "${RUST_TOOLCHAIN}" >/dev/null
fi
echo "cargo: $(cargo --version)"

echo ""
echo "=========================================="
echo "Setting up Verus ${VERUS_VERSION} for ${PLATFORM}"
echo "=========================================="

mkdir -p "$INSTALL_DIR"

if [ -f "$EXTRACTED_DIR/cargo-verus" ]; then
  echo "Verus already installed at $EXTRACTED_DIR — skipping download"
else
  echo "Downloading $ASSET ..."
  curl -fL --progress-bar -o "$INSTALL_DIR/$ASSET" "$URL"
  echo "Extracting ..."
  (cd "$INSTALL_DIR" && unzip -q -o "$ASSET" && rm "$ASSET")
fi

VERUS_PATH_ABS="$PROJECT_ROOT/$EXTRACTED_DIR"

if [ ! -f "$VERUS_PATH_ABS/cargo-verus" ]; then
  echo "Error: cargo-verus not found at $VERUS_PATH_ABS after extraction"
  exit 1
fi

cat > verus.config <<EOF
# Auto-generated by setup.sh — edit VERUS_PATH if you move the toolchain.
VERUS_PATH=$VERUS_PATH_ABS
EOF

echo ""
echo "Wrote verus.config:"
echo "  VERUS_PATH=$VERUS_PATH_ABS"
echo ""
echo "Done. Try: cd lion-liveness && ./verify.sh"
